---

- name: install zsh and dependencies
  become: yes
  include: "os_family/{{ ansible_os_family }}.yml"

- name: use some modules for zsh
  include: "modules.yml"

- name: change shell from bash to zsh
  user:
    name: "{{ item.name }}"
    shell: /bin/zsh
  with_items: "{{ zsh_users }}"
