---

- name: install zsh and dependencies
  become: yes
  include_tasks: "os_family/{{ ansible_os_family }}.yml"

- name: use some modules for zsh
  import_tasks: "modules.yml"

- name: change shells to zsh
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ zsh_users }}"
